emit:
  - "typespec-electrodb-emitter"
options:
  "typespec-electrodb-emitter":
    package-name: "@demo/demo-entities"
    package-version: "2.0.42"
    emitter-output-dir: "{project-root}/demo-entities"